steps:
  -   id: 'Run docker-compose'
      name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
      args: ['-f','PHP_8.0.2_FPM_Alpine_3.13/docker-compose.yaml','up','-d']

  -   id: 'Show docker-php-entrypoint content'
      name: 'gcr.io/cloud-builders/docker'
      args: ['exec','-t','php802a313','cat','/usr/local/bin/docker-php-entrypoint']

